openapi: 3.0.0
info:
  title: zssn
  version: '1.0'
servers:
  - url: 'http://localhost'
paths:
  /api/survivors/:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/survivor.v1.yaml
              examples:
                example-1: {}
    parameters: []
components:
  schemas: {}
